In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

train_df= pd.read_csv(r'C:\Users\asus\Desktop\stats\nlp\train_2kmZucJ.csv')

train_df.head(10)

id  label                                              tweet
0   1      0  #fingerprint #Pregnancy Test https://goo.gl/h1...
1   2      0  Finally a transparant silicon case ^^ Thanks t...
2   3      0  We love this! Would you go? #talk #makememorie...
3   4      0  I'm wired I know I'm George I was made that wa...
4   5      1  What amazing service! Apple won't even talk to...
5   6      1  iPhone software update fucked up my phone big ...
6   7      0  Happy for us .. #instapic #instadaily #us #son...
7   8      0  New Type C charger cable #UK http://www.ebay.c...
8   9      0  Bout to go shopping again listening to music #...
9  10      0  Photo: #fun #selfie #pool #water #sony #camera...

In [219]:
test_df= pd.read_csv(r'C:\Users\asus\Desktop\stats\nlp\test_oJQbWVk.csv')

test_df.head(10)

id                                              tweet
0  7921  I hate the new #iphone upgrade. Won't let me d...
1  7922  currently shitting my fucking pants. #apple #i...
2  7923  I'd like to puts some CD-ROMS on my iPad, is t...
3  7924  My ipod is officially dead. I lost all my pict...
4  7925  Been fighting iTunes all night! I only want th...
5  7926  #Repost @getbakednfried with repostapp ・・・ to ...
6  7927  This new apple software update is really doing...
7  7928  BABY #iPhone #iphone6s #gold #new #apple #appl...
8  7929  I'm confused...why did I have to take the time...
9  7930  Fruit just tastes better when you pick it your...

In [3]:
train_df.shape

(7920, 3)

In [4]:
test_df.shape

(1953, 2)

In [50]:
train_df = train_df.drop(columns = ['id'])

In [51]:
print(train_df.loc[train_df['label']==1].count())
print(train_df.loc[train_df['label']==0].count())

label    2026
tweet    2026
dtype: int64
label    5894
tweet    5894
dtype: int64


In [52]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(train_df, test_size = 0.35, random_state = 12)
print(train)
print(test)

      label                                              tweet
6513      1  Still pissed off at this gay downloading shit....
5816      0  Triple selfie between label meetings! #shakesh...
4628      0  The #Samsung #Galaxy #S3 #4G is so good. I'm w...
2767      0  We played with a flour. #my #girl #sweet #fun ...
2034      1  And another Apple charger bites the dust. $25 ...
...     ...                                                ...
7409      1  Safari sucks so bigtime on Windows that now ev...
3325      0  Walk on the Beach - Beat Timed Grime (TeknoAXE...
1414      0  Sister love. #sister #sisters #text #screensho...
5787      1  apple is giving me the biggest anxiety attack ...
5963      0  Retweeting @thescw: Smitten: http://flic.kr/p/...

[5148 rows x 2 columns]
      label                                              tweet
4888      1  When your new phone has even more problems tha...
1371      1  Is anyone else missing the YouTube icon #Apple...
520       0  We are all ONE hu

In [94]:
y_train = train.iloc[:, :1].values  

y_train



array([[1],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]], dtype=int64)

In [95]:
y_test = test.iloc[:, :1].values  

y_test


array([[1],
       [1],
       [0],
       ...,
       [0],
       [1],
       [0]], dtype=int64)

In [96]:
x_train = train.iloc[:, 1] 
x_train.reset_index(drop=True, inplace=True)
x_train


0       Still pissed off at this gay downloading shit....
1       Triple selfie between label meetings! #shakesh...
2       The #Samsung #Galaxy #S3 #4G is so good. I'm w...
3       We played with a flour. #my #girl #sweet #fun ...
4       And another Apple charger bites the dust. $25 ...
                              ...                        
5143    Safari sucks so bigtime on Windows that now ev...
5144    Walk on the Beach - Beat Timed Grime (TeknoAXE...
5145    Sister love. #sister #sisters #text #screensho...
5146    apple is giving me the biggest anxiety attack ...
5147    Retweeting @thescw: Smitten: http://flic.kr/p/...
Name: tweet, Length: 5148, dtype: object

In [97]:
x_test = test.iloc[:, 1] 
x_test.reset_index(drop=True, inplace=True)
x_test

0       When your new phone has even more problems tha...
1       Is anyone else missing the YouTube icon #Apple...
2       We are all ONE human Family #pakistan #humanri...
3       Just ordered the 24" #Apple #Cinema #Display.....
4       Samsung Galaxy S9+ Plus Dual Sim G965FD 6GB RA...
                              ...                        
2767    I love and am committed to #apple products but...
2768    Gain Followers RT This MUST FOLLOW ME I FOLLOW...
2769    Well, well, what do we have here? #Google #And...
2770    my phone is completely frozen and it wont turn...
2771    Photo: Oh #days. #Samsung #Galaxy #Note #2 #He...
Name: tweet, Length: 2772, dtype: object

In [190]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
#fit_transform is the same as first fit and then transform
x_train_vectors = vectorizer.fit_transform(x_train)

x_test_vectors = vectorizer.transform(x_test)
x_train_vectors[0]

<1x16919 sparse matrix of type '<class 'numpy.int64'>'
	with 18 stored elements in Compressed Sparse Row format>

## Classification

In [191]:
#Linear SVM

from sklearn.svm import SVC

clf_svm = SVC(kernel = 'linear')

clf_svm.fit(x_train_vectors ,np.ravel(y_train,order='C'))

print(x_test[14])

clf_svm.predict(x_test_vectors[14])


This is what happens when @eilidhpat0nn_ gets an iPhone..#iPhone #iMessage #random #child #her #tho http://instagr.am/p/WfVgukGfzc/


array([0], dtype=int64)

In [192]:
from sklearn.tree import DecisionTreeClassifier

clf_dec = DecisionTreeClassifier()

clf_dec.fit(x_train_vectors ,y_train)

print(x_test[1])
clf_dec.predict(x_test_vectors[1])

Is anyone else missing the YouTube icon #Apple #BassJesusProblems #BassJesus #wtf


array([0], dtype=int64)

In [193]:
from sklearn.linear_model import LogisticRegression

clf_log = LogisticRegression()
clf_log.fit(x_train_vectors ,np.ravel(y_train,order='C'))


print(x_test[12])
clf_dec.predict(x_test_vectors[12])

I always hated #Samsung in most of d aspects.n It proved it.It Made my Favorite Companies reputation Go into Drain.


array([0], dtype=int64)

In [194]:
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier

clf_ada = AdaBoostClassifier()
clf_ada.fit(x_train_vectors ,np.ravel(y_train,order='C'))

print(x_test[12])
clf_dec.predict(x_test_vectors[12])

I always hated #Samsung in most of d aspects.n It proved it.It Made my Favorite Companies reputation Go into Drain.


array([0], dtype=int64)

In [195]:
from sklearn.naive_bayes import GaussianNB

clf_gnb = GaussianNB()
clf_gnb.fit(x_train_vectors.toarray() ,np.ravel(y_train,order='C'))

print(x_test[12])
clf_dec.predict(x_test_vectors[12])

I always hated #Samsung in most of d aspects.n It proved it.It Made my Favorite Companies reputation Go into Drain.


array([0], dtype=int64)

In [196]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

clf_qda = QuadraticDiscriminantAnalysis()
clf_qda.fit(x_train_vectors.toarray() ,np.ravel(y_train,order='C'))

print(x_test[12])
clf_dec.predict(x_test_vectors[12])

C:\Users\asus\anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:691: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


I always hated #Samsung in most of d aspects.n It proved it.It Made my Favorite Companies reputation Go into Drain.


array([0], dtype=int64)

In [197]:
from sklearn.ensemble import RandomForestClassifier
clf_rfc = RandomForestClassifier(n_estimators=100, class_weight= {0:.5, 1:.5})
clf_rfc.fit(x_train_vectors ,np.ravel(y_train,order='C'))


print(x_test[12])
clf_rfc.predict(x_test_vectors[12])

I always hated #Samsung in most of d aspects.n It proved it.It Made my Favorite Companies reputation Go into Drain.


array([0], dtype=int64)

In [198]:
from sklearn.metrics import f1_score
f1_score(y_test, clf_svm.predict(x_test_vectors), average = None, labels = [0,1])

array([0.91348974, 0.75619835])

In [199]:
f1_score(y_test, clf_dec.predict(x_test_vectors), average = None, labels = [0,1])

array([0.89855781, 0.71438403])

In [200]:
f1_score(y_test, clf_log.predict(x_test_vectors), average = None, labels = [0,1])

array([0.92514021, 0.78724879])

In [201]:
f1_score(y_test, clf_ada.predict(x_test_vectors), average = None, labels = [0,1])

array([0.91613536, 0.76671214])

In [202]:
f1_score(y_test, clf_gnb.predict(x_test_vectors.toarray()), average = None, labels = [0,1])

array([0.87242592, 0.67477593])

In [203]:
f1_score(y_test, clf_qda.predict(x_test_vectors.toarray()), average = None, labels = [0,1])

array([0.07358491, 0.42640187])

In [204]:
f1_score(y_test, clf_rfc.predict(x_test_vectors), average = None, labels = [0,1])

array([0.92123872, 0.77616078])

In [205]:
from sklearn.linear_model import LogisticRegression

clf_log = LogisticRegression(class_weight= {0:.25, 1:.75})
clf_log.fit(x_train_vectors ,np.ravel(y_train,order='C'))


print(x_test[12])
clf_log.predict(x_test_vectors[12])

I always hated #Samsung in most of d aspects.n It proved it.It Made my Favorite Companies reputation Go into Drain.


array([0], dtype=int64)

In [206]:
f1_score(y_test, clf_log.predict(x_test_vectors), average = None, labels = [0,1])

array([0.92916984, 0.82616822])

In [207]:
test_df.head()

id                                              tweet
0  7921  I hate the new #iphone upgrade. Won't let me d...
1  7922  currently shitting my fucking pants. #apple #i...
2  7923  I'd like to puts some CD-ROMS on my iPad, is t...
3  7924  My ipod is officially dead. I lost all my pict...
4  7925  Been fighting iTunes all night! I only want th...

In [209]:
x_testfile = test_df.iloc[:, 1] 
x_testfile.reset_index(drop=True, inplace=True)

x_testfile_vectors = vectorizer.transform(x_testfile)
x_testfile_vectors[0]
Y= clf_log.predict(x_testfile_vectors)
Y

array([1, 1, 1, ..., 1, 1, 0], dtype=int64)

In [220]:
test_df['label']= Y
test_df

id                                              tweet  label
0     7921  I hate the new #iphone upgrade. Won't let me d...      1
1     7922  currently shitting my fucking pants. #apple #i...      1
2     7923  I'd like to puts some CD-ROMS on my iPad, is t...      1
3     7924  My ipod is officially dead. I lost all my pict...      1
4     7925  Been fighting iTunes all night! I only want th...      1
...    ...                                                ...    ...
1948  9869  #SamsungGalaxyNote7 Explodes, Burns 6-Year-Old...      0
1949  9870  Now Available - Hoodie. Check it out here - ht...      0
1950  9871  There goes a crack right across the screen. If...      1
1951  9872  @codeofinterest as i said #Adobe big time we m...      1
1952  9873  Finally I got it .. thanx my father .. #Samsun...      0

[1953 rows x 3 columns]

In [221]:
columns_titles = ["id","label","tweet"]
test_df=test_df.reindex(columns=columns_titles)

In [222]:
test_df

id  label                                              tweet
0     7921      1  I hate the new #iphone upgrade. Won't let me d...
1     7922      1  currently shitting my fucking pants. #apple #i...
2     7923      1  I'd like to puts some CD-ROMS on my iPad, is t...
3     7924      1  My ipod is officially dead. I lost all my pict...
4     7925      1  Been fighting iTunes all night! I only want th...
...    ...    ...                                                ...
1948  9869      0  #SamsungGalaxyNote7 Explodes, Burns 6-Year-Old...
1949  9870      0  Now Available - Hoodie. Check it out here - ht...
1950  9871      1  There goes a crack right across the screen. If...
1951  9872      1  @codeofinterest as i said #Adobe big time we m...
1952  9873      0  Finally I got it .. thanx my father .. #Samsun...

[1953 rows x 3 columns]

In [229]:
test_df = test_df.drop(columns = ["tweet"])
test_df

id  label
0     7921      1
1     7922      1
2     7923      1
3     7924      1
4     7925      1
...    ...    ...
1948  9869      0
1949  9870      0
1950  9871      1
1951  9872      1
1952  9873      0

[1953 rows x 2 columns]

In [230]:
test_df.to_csv(r'C:\Users\asus\Desktop\stats\nlp\log_fixedmodel_pred.csv', index=False)